-- Apply missing columns safely; skip if already exist
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS username VARCHAR(255) NOT NULL AFTER email,
  ADD COLUMN IF NOT EXISTS displayName VARCHAR(255) NOT NULL AFTER username,
  ADD COLUMN IF NOT EXISTS role VARCHAR(50) NOT NULL DEFAULT 'USER' AFTER displayName,
  ADD COLUMN IF NOT EXISTS isPremium BOOLEAN NOT NULL DEFAULT 0 AFTER role,
  ADD COLUMN IF NOT EXISTS avatarUrl VARCHAR(512) NULL AFTER status,
  ADD COLUMN IF NOT EXISTS accountStatus VARCHAR(20) NOT NULL DEFAULT 'good' AFTER avatarUrl,
  ADD COLUMN IF NOT EXISTS lastSeen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER accountStatus,
  ADD COLUMN IF NOT EXISTS updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER createdAt;

-- Rename password column if needed
ALTER TABLE users CHANGE password_hash passwordHash VARCHAR(255) NOT NULL;
