ALTER TABLE users
  ADD COLUMN IF NOT EXISTS totpSecret VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS totpEnabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS totpRecoveryCodes TEXT NULL;
