-- Prisma-aligned schema (MySQL) for Pasus
-- Generated from schema.prisma

-- Enum definitions
CREATE TABLE IF NOT EXISTS enum_placeholder (
  dummy INT
);
DROP TABLE enum_placeholder;

-- Users
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(191) PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  username VARCHAR(255) UNIQUE NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'USER',
  isPremium BOOLEAN NOT NULL DEFAULT FALSE,
  displayName VARCHAR(255) NOT NULL,
  passwordHash VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'offline',
  bio TEXT,
  avatarUrl VARCHAR(512),
  accountStatus VARCHAR(20) NOT NULL DEFAULT 'good',
  lastSeen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  emailVerified BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id VARCHAR(191) PRIMARY KEY,
  tokenHash VARCHAR(255) UNIQUE NOT NULL,
  userId VARCHAR(191) NOT NULL,
  expiresAt DATETIME NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revokedAt DATETIME,
  userAgent VARCHAR(255),
  ipAddress VARCHAR(64),
  INDEX idx_refresh_user (userId),
  CONSTRAINT fk_refresh_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friendships (
  id VARCHAR(191) PRIMARY KEY,
  initiatorId VARCHAR(191) NOT NULL,
  targetId VARCHAR(191) NOT NULL,
  status ENUM('PENDING','ACCEPTED','DECLINED','BLOCKED') NOT NULL DEFAULT 'PENDING',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_friend_pair (initiatorId, targetId),
  INDEX idx_friend_target (targetId),
  CONSTRAINT fk_friend_initiator FOREIGN KEY (initiatorId) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_friend_target FOREIGN KEY (targetId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS conversations (
  id VARCHAR(191) PRIMARY KEY,
  type ENUM('DM','GROUP') NOT NULL DEFAULT 'DM',
  title VARCHAR(255),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conversation_participants (
  id VARCHAR(191) PRIMARY KEY,
  conversationId VARCHAR(191) NOT NULL,
  userId VARCHAR(191) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'member',
  lastReadAt DATETIME,
  UNIQUE KEY uniq_conv_user (conversationId, userId),
  INDEX idx_conv_part_user (userId),
  CONSTRAINT fk_conv_part_conv FOREIGN KEY (conversationId) REFERENCES conversations(id) ON DELETE CASCADE,
  CONSTRAINT fk_conv_part_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS messages (
  id VARCHAR(191) PRIMARY KEY,
  conversationId VARCHAR(191) NOT NULL,
  senderId VARCHAR(191) NOT NULL,
  body TEXT NOT NULL,
  aiContext JSON,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_msg_conv (conversationId),
  CONSTRAINT fk_msg_conv FOREIGN KEY (conversationId) REFERENCES conversations(id) ON DELETE CASCADE,
  CONSTRAINT fk_msg_sender FOREIGN KEY (senderId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notifications (
  id VARCHAR(191) PRIMARY KEY,
  userId VARCHAR(191) NOT NULL,
  type VARCHAR(100) NOT NULL,
  payload JSON NOT NULL,
  readAt DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_notif_user (userId),
  CONSTRAINT fk_notif_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ai_sessions (
  id VARCHAR(191) PRIMARY KEY,
  userId VARCHAR(191),
  sessionKey VARCHAR(191),
  prompt TEXT NOT NULL,
  response TEXT,
  tokensUsed INT NOT NULL DEFAULT 0,
  mode VARCHAR(50) NOT NULL DEFAULT 'app',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completedAt DATETIME,
  latencyMs INT,
  chunkCount INT,
  avgChunkMs INT,
  safetyFlag VARCHAR(100),
  INDEX idx_ai_sessionKey (sessionKey),
  CONSTRAINT fk_ai_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id VARCHAR(191) PRIMARY KEY,
  userId VARCHAR(191),
  action VARCHAR(255) NOT NULL,
  metadata JSON,
  ipAddress VARCHAR(64),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_audit_user (userId),
  CONSTRAINT fk_audit_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS servers (
  id VARCHAR(191) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type ENUM('GROUP','SERVER','COMMUNITY') NOT NULL DEFAULT 'SERVER',
  iconUrl VARCHAR(512),
  ownerId VARCHAR(191) NOT NULL,
  description TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_server_owner FOREIGN KEY (ownerId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS server_memberships (
  id VARCHAR(191) PRIMARY KEY,
  serverId VARCHAR(191) NOT NULL,
  userId VARCHAR(191) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'member',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_server_user (serverId, userId),
  INDEX idx_member_user (userId),
  CONSTRAINT fk_member_server FOREIGN KEY (serverId) REFERENCES servers(id) ON DELETE CASCADE,
  CONSTRAINT fk_member_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS channels (
  id VARCHAR(191) PRIMARY KEY,
  serverId VARCHAR(191) NOT NULL,
  name VARCHAR(255) NOT NULL,
  topic TEXT,
  type ENUM('TEXT','VOICE','ANNOUNCEMENT','AI','VIDEO') NOT NULL DEFAULT 'TEXT',
  createdById VARCHAR(191) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_channel_server FOREIGN KEY (serverId) REFERENCES servers(id) ON DELETE CASCADE,
  CONSTRAINT fk_channel_creator FOREIGN KEY (createdById) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS channel_messages (
  id VARCHAR(191) PRIMARY KEY,
  channelId VARCHAR(191) NOT NULL,
  senderId VARCHAR(191) NOT NULL,
  body TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ch_msg_channel (channelId),
  CONSTRAINT fk_ch_msg_channel FOREIGN KEY (channelId) REFERENCES channels(id) ON DELETE CASCADE,
  CONSTRAINT fk_ch_msg_sender FOREIGN KEY (senderId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS server_roles (
  id VARCHAR(191) PRIMARY KEY,
  serverId VARCHAR(191) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  permissions JSON NOT NULL,
  isDefault BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_server_role (serverId, name),
  CONSTRAINT fk_role_server FOREIGN KEY (serverId) REFERENCES servers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS server_membership_roles (
  id VARCHAR(191) PRIMARY KEY,
  membershipId VARCHAR(191) NOT NULL,
  roleId VARCHAR(191) NOT NULL,
  UNIQUE KEY uniq_member_role (membershipId, roleId),
  INDEX idx_member_role_role (roleId),
  CONSTRAINT fk_member_role_membership FOREIGN KEY (membershipId) REFERENCES server_memberships(id) ON DELETE CASCADE,
  CONSTRAINT fk_member_role_role FOREIGN KEY (roleId) REFERENCES server_roles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS server_invites (
  id VARCHAR(191) PRIMARY KEY,
  code VARCHAR(191) UNIQUE NOT NULL,
  serverId VARCHAR(191) NOT NULL,
  createdById VARCHAR(191) NOT NULL,
  maxUses INT,
  uses INT NOT NULL DEFAULT 0,
  expiresAt DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_invite_server FOREIGN KEY (serverId) REFERENCES servers(id) ON DELETE CASCADE,
  CONSTRAINT fk_invite_creator FOREIGN KEY (createdById) REFERENCES users(id) ON DELETE CASCADE
);

-- Server templates
CREATE TABLE IF NOT EXISTS server_templates (
  id VARCHAR(191) PRIMARY KEY,
  ownerUserId VARCHAR(191) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  data JSON NOT NULL,
  isPublic BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_template_owner FOREIGN KEY (ownerUserId) REFERENCES users(id) ON DELETE CASCADE
);

-- Onboarding settings on servers
ALTER TABLE servers
  ADD COLUMN IF NOT EXISTS type ENUM('GROUP','SERVER','COMMUNITY') NOT NULL DEFAULT 'SERVER',
  ADD COLUMN IF NOT EXISTS welcomeChannelId VARCHAR(191),
  ADD COLUMN IF NOT EXISTS welcomeMessageTemplate TEXT;

CREATE TABLE IF NOT EXISTS call_sessions (
  id VARCHAR(191) PRIMARY KEY,
  channelId VARCHAR(191) NOT NULL,
  serverId VARCHAR(191) NOT NULL,
  initiatorId VARCHAR(191) NOT NULL,
  mediaType ENUM('VOICE','VIDEO') NOT NULL,
  status ENUM('RINGING','ACTIVE','ENDED') NOT NULL DEFAULT 'RINGING',
  startedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  endedAt DATETIME,
  endedReason TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  metadata JSON,
  INDEX idx_call_channel (channelId),
  INDEX idx_call_server (serverId),
  CONSTRAINT fk_call_channel FOREIGN KEY (channelId) REFERENCES channels(id) ON DELETE CASCADE,
  CONSTRAINT fk_call_server FOREIGN KEY (serverId) REFERENCES servers(id) ON DELETE CASCADE,
  CONSTRAINT fk_call_initiator FOREIGN KEY (initiatorId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS call_participants (
  id VARCHAR(191) PRIMARY KEY,
  sessionId VARCHAR(191) NOT NULL,
  userId VARCHAR(191) NOT NULL,
  status ENUM('INVITED','JOINED','LEFT') NOT NULL DEFAULT 'INVITED',
  joinedAt DATETIME,
  leftAt DATETIME,
  muted BOOLEAN NOT NULL DEFAULT FALSE,
  videoMuted BOOLEAN NOT NULL DEFAULT FALSE,
  qualityNotes TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_call_user (sessionId, userId),
  INDEX idx_call_part_user (userId),
  CONSTRAINT fk_call_part_session FOREIGN KEY (sessionId) REFERENCES call_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_call_part_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id VARCHAR(191) PRIMARY KEY,
  userId VARCHAR(191) NOT NULL UNIQUE,
  stripeCustomerId VARCHAR(255) NOT NULL,
  stripeSubscriptionId VARCHAR(255) NOT NULL,
  plan ENUM('FREE','PREMIUM_MONTHLY','PREMIUM_YEARLY') NOT NULL DEFAULT 'PREMIUM_MONTHLY',
  status ENUM('ACTIVE','TRIALING','CANCELED','INCOMPLETE','INCOMPLETE_EXPIRED','PAST_DUE','UNPAID','EXPIRED') NOT NULL DEFAULT 'ACTIVE',
  currentPeriodEnd DATETIME NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_sub_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

-- Moderation
CREATE TABLE IF NOT EXISTS moderation_statuses (
  userId VARCHAR(191) PRIMARY KEY,
  currentStage ENUM('NONE','WARNING_1','WARNING_2','WARNING_3','WARNING_4','TERMINATED') NOT NULL DEFAULT 'NONE',
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_mod_status_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS moderation_actions (
  id VARCHAR(191) PRIMARY KEY,
  userId VARCHAR(191) NOT NULL,
  moderatorId VARCHAR(191) NOT NULL,
  stage ENUM('NONE','WARNING_1','WARNING_2','WARNING_3','WARNING_4','TERMINATED') NOT NULL,
  reasonCode VARCHAR(100) NOT NULL,
  reasonText VARCHAR(255) NOT NULL,
  notes TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_mod_user (userId),
  INDEX idx_mod_moderator (moderatorId),
  CONSTRAINT fk_mod_action_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_mod_action_moderator FOREIGN KEY (moderatorId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_reports (
  id VARCHAR(191) PRIMARY KEY,
  reporterId VARCHAR(191) NOT NULL,
  reportedUserId VARCHAR(191) NOT NULL,
  reasonCode VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  status ENUM('NEW','REVIEWED','DISMISSED') NOT NULL DEFAULT 'NEW',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_report_reported (reportedUserId),
  INDEX idx_report_reporter (reporterId),
  CONSTRAINT fk_report_reporter FOREIGN KEY (reporterId) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_report_user FOREIGN KEY (reportedUserId) REFERENCES users(id) ON DELETE CASCADE
);

-- Unified moderation reports (users, messages, groups)
CREATE TABLE IF NOT EXISTS reports (
  id VARCHAR(191) PRIMARY KEY,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reporter_id VARCHAR(191) NOT NULL,
  target_type ENUM('USER','MESSAGE','GROUP') NOT NULL,
  target_id VARCHAR(191) NOT NULL,
  group_id VARCHAR(191),
  channel_id VARCHAR(191),
  reason_code VARCHAR(100) NOT NULL,
  reason_text TEXT,
  status ENUM('OPEN','IN_REVIEW','RESOLVED','DISMISSED') NOT NULL DEFAULT 'OPEN',
  handled_by VARCHAR(191),
  handled_at DATETIME,
  notes TEXT,
  INDEX idx_reports_status (status),
  INDEX idx_reports_target (target_type, target_id),
  INDEX idx_reports_group (group_id),
  INDEX idx_reports_reporter (reporter_id),
  CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_reports_group FOREIGN KEY (group_id) REFERENCES servers(id) ON DELETE SET NULL,
  CONSTRAINT fk_reports_channel FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS friends (
    id VARCHAR(36) PRIMARY KEY,
    userA VARCHAR(36) NOT NULL,
    userB VARCHAR(36) NOT NULL,
    status VARCHAR(20) DEFAULT 'pending',
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userA) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (userB) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE KEY unique_friendship (userA, userB)
);

CREATE TABLE IF NOT EXISTS voice_participants (
    channelId VARCHAR(36) NOT NULL,
    userId VARCHAR(36) NOT NULL,
    peerId VARCHAR(100) NOT NULL,
    muted BOOLEAN DEFAULT FALSE,
    deafened BOOLEAN DEFAULT FALSE,
    joinedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    lastKeepAlive DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (channelId, userId),
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
